spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sensebot_outbound_db?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: chenzhen

  redis:
    username: root
    url: 127.0.0.1
    port: 6379

  activemq:
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:61616
jms:
  uploadQueue:
    name: FILE_UPLOAD
  transferQueue:
    name: DATA_TRANSFER
mybatis:
  type-aliases-package: com.sense.newots.object.entity
  mapper-locations: classpath:mappers/*Mapper.xml
server:
  port: 8081
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true